import Logger from '../logger';
import { isMusl } from './is_musl';

let minicoreModule: typeof import('./dist') | null;
let minicoreVersion: string;

// NOTE:
// Custom loader instead of napi-rs autogenerated binding file because:
// - napi-rs tries to require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH) which might be a security risk
// - napi-rs tries to require('packageName-platform-arch') which we don't publish yet
// - we want lazy require to ensure that logger is set before the require attempt
function getMinicoreModule() {
  if (minicoreModule !== undefined) {
    return minicoreModule;
  }

  try {
    const { platform, arch } = process;
    let suffix = '';
    if (platform === 'linux') {
      suffix = isMusl() ? '-musl' : '-gnu';
    } else if (platform === 'win32') {
      suffix = 'msvc';
    }
    // TODO:
    // we don't collect enough telemetry to understand which binary is from this list
    // https://github.com/napi-rs/napi-rs/blob/main/triples/target-list
    minicoreModule = require(`./dist/sf_mini_core.${platform}-${arch}${suffix}.node`);
  } catch (error) {
    minicoreModule = null;
    Logger().debug('Error loading minicore:', error);
  }

  return minicoreModule;
}

export function getMinicoreVersion() {
  // NOTE:
  // minicoreVersion is cached as each call of node addon has memory overhead
  if (minicoreVersion) {
    return minicoreVersion;
  }

  const minicoreModule = getMinicoreModule();
  minicoreVersion = minicoreModule ? minicoreModule.sfCoreFullVersion() : 'failed-to-load';

  return minicoreVersion;
}
