import Logger from '../logger';
import { isMusl } from './is_musl';

type MinicoreStatus = {
  version: string | null;
  binaryName: string | null;
  errorType: string | null;
  errorDetails: Error | null;
};

export const minicoreStatus: MinicoreStatus = {
  version: null,
  binaryName: null,
  errorType: null,
  errorDetails: null,
};

if (process.env.SNOWFLAKE_DISABLE_MINICORE) {
  minicoreStatus.errorType = 'Minicore is disabled with SNOWFLAKE_DISABLE_MINICORE env variable';
} else {
  try {
    minicoreStatus.binaryName = getBinaryName();

    // eval('require') prevents bundlers (esbuild, webpack, etc.) from statically analyzing
    // and attempting to bundle .node native addon files
    // oxlint-disable-next-line no-eval
    const minicoreModule = eval('require')(
      `./binaries/${minicoreStatus.binaryName}`,
    ) as typeof import('./binaries');

    minicoreStatus.version = minicoreModule.sfCoreFullVersion();
  } catch (error: unknown) {
    minicoreStatus.errorType = isBinaryIgnoredByBundlers(error)
      ? 'Binary is missing from the bundle'
      : 'Failed to load binary';

    if (error instanceof Error) {
      minicoreStatus.errorDetails = error;
    }
  }
}

// NOTE:
// Custom loader instead of napi-rs autogenerated binding file because:
// - napi-rs tries to require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH) which might be a security risk
// - napi-rs tries to require('packageName-platform-arch') which we don't publish yet
export function getBinaryName() {
  const { platform, arch } = process;
  const suffix: string[] = [platform, arch];

  if (platform === 'linux') {
    suffix.push(isMusl() ? 'musl' : 'gnu');
  } else if (platform === 'win32') {
    suffix.push('msvc');
  }

  return `sf_mini_core_0.0.1.${suffix.join('-')}.node`;
}

let isMinicoreStatusLogged = false;
export function getMinicoreStatus() {
  // NOTE:
  // At the time of minicore loading, the logger isn't initialized, so we hold the error until
  // the first getMinicoreStatus() call
  if (!isMinicoreStatusLogged) {
    Logger().debug(
      'Minicore status: binaryName - %s, error - %s',
      minicoreStatus.binaryName,
      minicoreStatus.errorDetails ?? minicoreStatus.errorType,
    );
    isMinicoreStatusLogged = true;
  }
  return minicoreStatus;
}

function isBinaryIgnoredByBundlers(error: unknown) {
  if (error instanceof Error) {
    const message = error.message;
    return (
      // eval('require') was ignored by bundlers
      message.startsWith('Cannot find module') ||
      // bundled code running in ESM environment
      message === 'require is not defined' ||
      // Windows: DLL mapped to a network path that the bundled app can't reach
      message === 'LoadLibrary failed: The network name cannot be found.' ||
      // Windows: DLL not found
      message === 'LoadLibrary failed: The specified module could not be found.'
    );
  } else {
    return false;
  }
}
