import Logger from '../logger';
import { isMusl } from './is_musl';

type MinicoreStatus = {
  version: string | null;
  binaryName: string | null;
  error: unknown | null;
};

export const minicoreStatus: MinicoreStatus = {
  version: null,
  binaryName: null,
  error: null,
};
let logDebugMinicoreError: unknown | null = null;

if (process.env.SNOWFLAKE_DISABLE_MINICORE) {
  minicoreStatus.error = 'Minicore is disabled with SNOWFLAKE_DISABLE_MINICORE env variable';
} else {
  try {
    minicoreStatus.binaryName = getBinaryName();

    // eval('require') prevents bundlers (esbuild, webpack, etc.) from statically analyzing
    // and attempting to bundle .node native addon files
    const minicoreModule = eval('require')(
      `./binaries/${minicoreStatus.binaryName}`,
    ) as typeof import('./binaries');

    minicoreStatus.version = minicoreModule.sfCoreFullVersion();
  } catch (error: unknown) {
    // NOTE:
    // minicoreStatus is pushed to telemetry, so we don't want the original error there as it might
    // contain sensitive information
    logDebugMinicoreError = error;
    minicoreStatus.error = 'Failed to load binary';
  }
}

// NOTE:
// Custom loader instead of napi-rs autogenerated binding file because:
// - napi-rs tries to require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH) which might be a security risk
// - napi-rs tries to require('packageName-platform-arch') which we don't publish yet
export function getBinaryName() {
  const { platform, arch } = process;
  const suffix: string[] = [platform, arch];

  if (platform === 'linux') {
    suffix.push(isMusl() ? 'musl' : 'gnu');
  } else if (platform === 'win32') {
    suffix.push('msvc');
  }

  return `sf_mini_core_0.0.1.${suffix.join('-')}.node`;
}

export function getMinicoreStatus() {
  // NOTE:
  // At the time of minicore loading, the logger isn't initialized, so we hold the error until
  // the first getMinicoreStatus() call
  if (logDebugMinicoreError) {
    Logger().debug('Error loading minicore: %s', logDebugMinicoreError);
    logDebugMinicoreError = null;
  }
  return minicoreStatus;
}
