FROM centos:6.10

COPY CentOS-Base.repo /etc/yum.repos.d/
CMD chmod 644 /etc/yum.repos.d/CentOS-Base.repo

RUN yum install -y yum-utils
RUN yum-config-manager --disable WANdisco-git
RUN yum-config-manager --disable okay
RUN yum-config-manager --disable base
RUN yum-config-manager --disable updates
RUN yum-config-manager --enable base
RUN yum-config-manager --enable updates
RUN yum-config-manager --enable extras

RUN yum install -y centos-release-scl;


# nvm environment variables
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 10.0.0

# node
RUN mkdir -p $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
COPY scripts/npmrc /root/.npmrc
RUN npm install npm@6.0 -g

# python
RUN yum-config-manager --add-repo http://repo.int.snowflakecomputing.com:81/repos/centos-sclo-rh
RUN yum -y install rh-python36
COPY scripts/python3.6.sh /usr/local/bin/python3.6
COPY scripts/python3.6.sh /usr/local/bin/python3
RUN chmod a+x /usr/local/bin/python3.6
RUN chmod a+x /usr/local/bin/python3
COPY scripts/pip.sh /usr/local/bin/pip
RUN chmod a+x /usr/local/bin/pip
RUN pip install -U pip
RUN pip install -U snowflake-connector-python

# aws
RUN pip install -U awscli
COPY scripts/aws.sh /usr/local/bin/aws
RUN chmod a+x /usr/local/bin/aws

# Development tools
RUN yum -y groupinstall "Development Tools" && \
    yum -y install zlib-devel

# git
RUN curl -o - https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.26.0.tar.gz | tar xfz - && \
    cd git-2.26.0 && \
    ./configure --prefix=/opt/git && make && make install && \
    ln -s /opt/git/bin/git /usr/local/bin/git

# zstd
RUN yum -y install epel-release
RUN yum -y install libzstd-devel

# jq
RUN yum -y install jq

# gosu
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.11/gosu-amd64"
RUN chmod +x /usr/local/bin/gosu
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Java
RUN yum -y install java-1.8.0-openjdk-devel

# workspace

RUN mkdir -p /home/user
RUN chmod 777 /home/user
WORKDIR /home/user

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
