const AuthenticationTypes =
{
  DEFAULT_AUTHENTICATOR: 'SNOWFLAKE', // default authenticator name
  EXTERNAL_BROWSER_AUTHENTICATOR: 'EXTERNALBROWSER',
  KEY_PAIR_AUTHENTICATOR: 'SNOWFLAKE_JWT',
  OAUTH_AUTHENTICATOR: 'OAUTH',
  USER_PWD_MFA_AUTHENTICATOR: 'USERNAME_PASSWORD_MFA',
  ID_TOKEN_AUTHENTICATOR: 'ID_TOKEN',
};

module.exports = AuthenticationTypes;