declare module 'asn1.js' {
  class BN {
    constructor(value: string | number | bigint | Buffer, base?: number);
    toString(base?: number): string;
    toNumber(): number;
    toBuffer(endian?: 'be' | 'le', length?: number): Buffer;
    clone(): BN;
    cmp(other: BN | string): number;
    eq(other: BN | string): boolean;
    gt(other: BN | string): boolean;
    lt(other: BN | string): boolean;
  }

  export const bignum: typeof BN;

  // Partial definition to cover only methods we use
  interface ASN1Builder {
    seq(): this;
    obj(...args: ASN1Builder[]): this;
    key(name: string): this;
    objid(): this;
    optional(): this;
    any(): this;
    explicit(tag: number): this;
    use(entity: ASN1Entity<unknown>): this;
    int(): this;
  }

  export interface ASN1Entity<T> {
    decode(data: Buffer | string, encoding?: 'der' | 'pem'): T;
    encode(data: T, encoding?: 'der' | 'pem'): Buffer;
  }

  export function define<T = unknown>(
    name: string,
    body: (this: ASN1Builder) => void,
  ): ASN1Entity<T>;
}

// NOTE:
// These definitions only cover the methods currently used in TypeScript codebase
// Mostly generated by AI
declare module 'asn1.js-rfc5280' {
  import { ASN1Entity } from 'asn1.js';

  type BaseExtension<TId extends string, TValue> = {
    extnID: TId;
    extnValue: TValue;
  };

  export interface AlgorithmIdentifier {
    algorithm: number[];
    parameters?: Buffer;
  }

  export type UnknownExtension = BaseExtension<string, unknown>;

  export type CrlDistributionPointsExtension = BaseExtension<
    'cRLDistributionPoints',
    {
      distributionPoint?: {
        type: 'fullName';
        value: {
          type: 'uniformResourceIdentifier' | 'dNSName';
          value: string;
        }[];
      };
    }[]
  >;

  export type IssuingDistributionPointExtension = BaseExtension<
    'issuingDistributionPoint',
    {
      distributionPoint: {
        type: 'fullName';
        value: {
          type: 'uniformResourceIdentifier' | 'dNSName';
          value: string;
        }[];
      };
      onlyContainsUserCerts?: boolean;
      onlyContainsCACerts?: boolean;
      indirectCRL?: boolean;
      onlyContainsAttributeCerts?: boolean;
    }
  >;

  // Value is in milliseconds since epoch
  type Time = { type: 'utcTime' | 'generalTime'; value: number };

  interface BitString {
    unused: number;
    data: Buffer;
  }

  interface SubjectPublicKeyInfo {
    algorithm: AlgorithmIdentifier;
    subjectPublicKey: BitString;
  }

  export interface NameRDNSequence {
    type: 'rdnSequence';
    value: any[];
  }

  interface Validity {
    notBefore: Time;
    notAfter: Time;
  }

  export interface TBSCertificate {
    version?: string;
    serialNumber: BN;
    signature: AlgorithmIdentifier;
    issuer: NameRDNSequence;
    validity: Validity;
    subject: NameRDNSequence;
    subjectPublicKeyInfo: SubjectPublicKeyInfo;
    extensions?: (CrlDistributionPointsExtension | UnknownExtension)[];
  }

  export interface TBSCertList {
    version?: BN;
    signature: AlgorithmIdentifier;
    issuer: NameRDNSequence;
    thisUpdate: Time;
    nextUpdate: Time;
    revokedCertificates: {
      userCertificate: BN;
      revocationDate: Time;
      crlEntryExtensions?: Extension[];
    }[];
    crlExtensions?: (IssuingDistributionPointExtension | UnknownExtension)[];
  }

  export interface CertificateDecoded {
    tbsCertificate: TBSCertificate;
    signatureAlgorithm: AlgorithmIdentifier;
    signature: BitString;
  }

  export interface CertificateListDecoded {
    tbsCertList: TBSCertList;
    signatureAlgorithm: AlgorithmIdentifier;
    signature: BitString;
  }

  const RFC5280: {
    AlgorithmIdentifier: ASN1Entity<AlgorithmIdentifier>;
    CertificateList: ASN1Entity<CertificateListDecoded>;
    TBSCertList: ASN1Entity<TBSCertList>;
    Certificate: ASN1Entity<CertificateDecoded>;
    SubjectPublicKeyInfo: ASN1Entity<SubjectPublicKeyInfo>;
  };

  export = RFC5280;
}
