name: Audit

permissions:
  contents: read

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - '**'

jobs:
  audit:
    name: Published package dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm i
      - run: npm audit --omit=dev
